### ISSUE TITLE
Hex invalid version

### ISSUE THREAD

**Issue by venadHD** [HackerExperience/Helix#403]
Today im triying to install HELIX to work with HEBorn, but at the moment of instalating HELIX output this error in the moment that try to get HEX dependencies
```
root@mainsv:/var/www/_HELIX/Helix-master# MIX_ENV=prod mix do deps.get, compile, release --env=prod
Resolving Hex dependencies...
** (Hex.Version.InvalidRequirementError) invalid requirement: "1.6.3 or 1.6.5 or 1.7.1 or 1.8.6 or ~> 1.9"
    (hex) lib/hex/version.ex:129: Hex.Version.parse_requirement!/2
    (hex) lib/hex/version.ex:47: anonymous fn/3 in Hex.Version.match?/3
    (hex) lib/hex/version.ex:139: Hex.Version.cache/2
    (elixir) lib/enum.ex:704: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:704: Enum.filter/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (hex) lib/hex/resolver.ex:205: Hex.Resolver.get_versions/4


09:32:51.323 [error] Process #PID<0.46.0> raised an exception
** (Hex.Version.InvalidRequirementError) invalid requirement: "1.6.3 or 1.6.5 or 1.7.1 or 1.8.6 or ~> 1.9"
    (hex) lib/hex/version.ex:129: Hex.Version.parse_requirement!/2
    (hex) lib/hex/version.ex:47: anonymous fn/3 in Hex.Version.match?/3
    (hex) lib/hex/version.ex:139: Hex.Version.cache/2
    (elixir) lib/enum.ex:704: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:704: Enum.filter/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (hex) lib/hex/resolver.ex:205: Hex.Resolver.get_versions/4

```

**Comment by PedroHLC** [comment]
Hi @venadHD 
Try the "non-production" way:
```sh
git clone $link
cd $repo
mix deps.get
mix ecto.reset
iex -S mix
```

**Comment by venadHD** [comment]
Now this are solved my installing first erlang and install elixir from the erlang  deviratiom

**Comment by PedroHLC** [comment]
Renato only uses BSD variants

**Comment by renatomassaro** [comment]
It works on any Linux distro though; our Travis build is tested on Ubuntu 14.04
